routes/web.php
<?php

// -----------------------------------------------------------------------------------------
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Cookie;

Route::get('/dev-protect', function() {
    \Debugbar::disable();
    return view('dev-protect');
})->name('dev-protect');

Route::post('/dev-protect', function() {
    $_username = 'einutech';
    $_password = 'ekoset14';

    $username = Request::input('username');
    $password = Request::input('password');

    if (($username == $_username) && ($password == $_password)) {
        Cookie::queue(Cookie::make('temp_login', true, 3600));
        return redirect('/');
    } else {
        echo "Wrong username or password";
    }
});
// -----------------------------------------------------------------------------------------

Route::get('/repulsive', function() {
    return view('repulsive');
});

Route::middleware(['dev.protect'])->group(function () {
    Route::get('/login', function() {
        Auth::loginUsingId(1, true);
        return redirect()->route('forum.index');
    });

    Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');

    Route::get('/', 'NewsController@index')->name('news.index');

    Route::get('/profile/{username}', 'ProfileController@show')->name('profile');

    Route::get('/forum', 'ForumController@index')->name('forum.index');
    Route::get('/forum/{slug}', 'ForumController@forum')->name('forum.forum');
    Route::get('/forum/{slug}/new', 'ForumController@new')->name('forum.new');
    Route::post('/forum/{slug}/new', 'ForumController@store');
    Route::get('/forum/thread/{slug}', 'ForumController@thread')->name('forum.thread');
    Route::post('/forum/thread/{slug}', 'ForumController@reply');
    Route::delete('/forum/thread/{slug}', 'ForumController@destroy');
    Route::get('/forum/thread/{slug}/lock', 'ForumController@lock')->name('forum.thread.lock');
    Route::get('/forum/thread/{slug}/pin', 'ForumController@pin')->name('forum.thread.pin');
    Route::get('/forum/thread/{slug}/feature', 'ForumController@feature')->name('forum.thread.feature');
    Route::get('/forum/thread/{slug}/edit', 'ForumController@edit')->name('forum.edit');
    Route::patch('/forum/thread/{slug}/edit', 'ForumController@update');
    Route::delete('/forum/replies/{slug}', 'ForumController@destroyReply')->name('forum.destroyReply');

    Route::get('/wallet', 'WalletController@index')->name('wallet.index');
    Route::get('/wallet/transactions', 'WalletController@transactions')->name('wallet.transactions');
    Route::get('/wallet/еxchange', 'WalletController@exchange')->name('wallet.exchange');
    Route::post('/wallet/еxchange', 'WalletController@exchangePost');
    Route::get('/wallet/deposit', 'WalletController@deposit')->name('wallet.deposit');
    Route::post('/wallet/deposit', 'WalletController@depositPost');
    Route::get('/wallet/send', 'WalletController@send')->name('wallet.send');
    Route::post('/wallet/send', 'WalletController@sendPost');

    Route::get('/help/support', 'HelpController@support')->name('help.support');
    Route::get('/help/contact', 'HelpController@contact')->name('help.contact');
    Route::get('/help/faq', 'HelpController@faq')->name('help.faq');
    Route::get('/help/ranks', 'HelpController@ranks')->name('help.ranks');
    Route::get('/help/levels', 'HelpController@levels')->name('help.levels');

    Route::get('/experience', 'ExperienceController@index')->name('experience.index');

    Route::get('/armory', 'ArmoryController@index')->name('armory.index');
});

app/Models/Misc/Level.php
<?php

namespace App\Models\Misc;

use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    protected $table = 'levels';
    protected $fillable = ['rank_id', 'level'];
    protected $hidden = ['created_at', 'updated_at', 'id'];

    protected static $max_level = 100;

    public function rank()
    {
        return $this->belongsTo(Rank::class);
    }

    /**
     * Constant that decides how much
     * experience you need to get level up
     *
     * @var int
     */
    private static $base = 150;

    /**
     * Constant that decides how much
     * daily points you receive
     *
     * @var int
     */
    private static $daily_base = 10;

    /**
     * Constant that decides the increase
     * of experience you need for each level
     *
     * @var float
     */
    private static $factor = 1.22;

    /**
     * Constant that decides the increase
     * of daily points you receive
     *
     * @var float
     */
    private static $daily_factor = 1.08;
    private static $daily_factor2 = 1.09;

    /**
     * Gets a level based on experience
     *
     * @param $experience
     * @return mixed
     */
    public static function get($experience)
    {
        $levels = self::levels();
        $max_level = self::max_level();

        foreach ($levels as $level => $xp) {
            if (array_key_exists($level + 1, $levels)) {
                if (intval($experience) < $levels[$level + 1]) {
                    $lvl = $level;
                    break;
                }
            } else {
                $lvl = $max_level;
                break;
            }
        }


        return self::where('level', $lvl)->firstOrFail();
    }

    /**
     * Returns required experience for that level
     *
     * @return mixed
     */
    public function getRequiredExperienceAttribute()
    {
        return static::levels()[$this->level];
    }

    /**
     * Returns daily points you receive on current level
     *
     * @return mixed
     */
    public function getDailyPointsAttribute()
    {
        return static::dailyPoints()[$this->level];
    }

    /**
     * Returns maximum level that a user can be
     *
     * @return mixed
     */
    private static function max_level()
    {
        return static::$max_level;
    }

    /**
     * Calculates experience required to get a certain level
     *
     * @return array
     */
    private static function levels()
    {
        $levels = [];
        $max_level = self::max_level();

        $levels[1] = 0;

        for ($level = 1; $level <= $max_level-1; $level++) {
            $levels[$level + 1] = round(self::$base * pow(self::$factor, $level + 1));
        }

        return $levels;
    }

    private static function dailyPoints()
    {
        $levels = [];
        $max_level = self::max_level();

        $levels[1] = 10;

        for ($level = 1; $level <= $max_level-1; $level++) {
            if ($level <= 90) {
                $levels[$level + 1] = round(self::$daily_base * pow(self::$daily_factor, $level + 1));
            } else {
                $levels[$level + 1] = round(self::$daily_base * pow(self::$daily_factor2, $level + 1));
            }
        }

        return $levels;
    }
}

app/Models/Misc/Rank.php
<?php

namespace App\Models\Misc;

use Illuminate\Database\Eloquent\Model;

class Rank extends Model
{
    protected $table = 'ranks';
    protected $fillable = ['name', 'badge_path', 'background_path', 'color'];
    protected $hidden = ['created_at', 'updated_at', 'badge_path', 'id'];
    protected $with = ['levels'];
    
    public function levels()
    {
        return $this->hasMany(Level::class);
    }

    public function getRequiredLevelAttribute()
    {
        $levels = $this->levels;
        $requiredLevel = 0;
        foreach ($levels as $level) {
            $requiredLevel = $level;

            if ($level->level < $requiredLevel->level) {
                break;
            }
        }

        return $requiredLevel;
    }
}

app/Http/Controllers/HelpController.php
<?php

namespace App\Http\Controllers;

use App\Models\Misc\Rank;
use App\Models\Misc\Level;
use Illuminate\Http\Request;

class HelpController extends Controller
{
    public function ranks()
    {
        $ranks = Rank::all();

        return view('help.ranks', [
            'ranks' => $ranks
        ]);
    }

    public function levels()
    {
        $levels = Level::all();

        return view('help.levels', [
            'levels' => $levels
        ]);
    }
}

resources/views/help/levels.blade.php
@extends('layouts.app')
@section('sidebar_active', 'help')
@section('subnav_active', 'levels')

@section('content')
    <einu-section class="help">
        @include('help.layouts.navigation')
        <einu-heading class="section-heading">Levels</einu-heading>

        <einu-grid>
            <einu-col size="M12 T12 D12">
                <einu-block class="section">
                    <einu-table>
                        <einu-table-header>
                            <einu-table-cell>Level</einu-table-cell>
                            <einu-table-cell>Rank</einu-table-cell>
                            <einu-table-cell>Daily points</einu-table-cell>
                        </einu-table-header>
                        @foreach ($levels as $level)
                            <einu-table-row>
                                <einu-table-cell>{{ $level->level }}</einu-table-cell>
                                <einu-table-cell>{{ $level->rank->name }}</einu-table-cell>
                                <einu-table-cell>{{ number_format($level->daily_points, 0) }} BRP</einu-table-cell>
                            </einu-table-row>
                        @endforeach
                    </einu-table>
                </einu-block>
            </einu-col>
        </einu-grid>
    </einu-section>
@endsection

resources/views/help/ranks.blade.php
@extends('layouts.app')
@section('sidebar_active', 'help')
@section('subnav_active', 'ranks')

@section('content')
    <einu-section class="help">
        @include('help.layouts.navigation')
        <einu-heading class="section-heading">Ranks</einu-heading>

        <einu-grid>
            @foreach ($ranks as $rank)
                <einu-col id="{{ str_slug($rank->name) }}" size="{{ $rank->name == 'Sentinel' ? 'M12 T12 D12' : 'M12 T12 D4' }}">
                    <einu-block class="section rank">
                        <einu-block class="background" style="background-image: url('{{ asset($rank->background_path) }}');">
                            <einu-heading style="background: transparent;" size="1">{{ $rank->name }}</einu-heading>

                            <img class="badge" src="{{ asset($rank->badge_path) }}" />
                            <einu-table>
                                <einu-table-row>
                                    <einu-table-cell>Required level</einu-table-cell>
                                    <einu-table-cell>{{ $rank->required_level->level }}</einu-table-cell>
                                </einu-table-row>
                                <einu-table-row>
                                    <einu-table-cell>Daily points</einu-table-cell>
                                    <einu-table-cell>{{ number_format($rank->required_level->daily_points, 2) }} BRP</einu-table-cell>
                                </einu-table-row>
                            </einu-table>
                        </einu-block>
                    </einu-block>
                </einu-col>
            @endforeach
        </einu-grid>
    </einu-section>
@endsection