routes/web.php
<?php

// -----------------------------------------------------------------------------------------
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Cookie;

Route::get('/dev-protect', function() {
    \Debugbar::disable();
    return view('dev-protect');
})->name('dev-protect');

Route::post('/dev-protect', function() {
    $_username = 'einutech';
    $_password = 'ekoset14';

    $username = Request::input('username');
    $password = Request::input('password');

    if (($username == $_username) && ($password == $_password)) {
        Cookie::queue(Cookie::make('temp_login', true, 3600));
        return redirect('/');
    } else {
        echo "Wrong username or password";
    }
});
// -----------------------------------------------------------------------------------------

Route::get('/repulsive', function() {
    return view('repulsive');
});

Route::middleware(['dev.protect'])->group(function () {
    Route::get('/login', function() {
        Auth::loginUsingId(1, true);
        return redirect()->route('forum.index');
    });

    Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');

    Route::get('/', 'NewsController@index')->name('news.index');

    Route::get('/profile/{username}', 'ProfileController@show')->name('profile');

    Route::get('/forum', 'ForumController@index')->name('forum.index');
    Route::get('/forum/{slug}', 'ForumController@forum')->name('forum.forum');
    Route::get('/forum/{slug}/new', 'ForumController@new')->name('forum.new');
    Route::post('/forum/{slug}/new', 'ForumController@store');
    Route::get('/forum/thread/{slug}', 'ForumController@thread')->name('forum.thread');
    Route::post('/forum/thread/{slug}', 'ForumController@reply');
    Route::delete('/forum/thread/{slug}', 'ForumController@destroy');
    Route::get('/forum/thread/{slug}/lock', 'ForumController@lock')->name('forum.thread.lock');
    Route::get('/forum/thread/{slug}/pin', 'ForumController@pin')->name('forum.thread.pin');
    Route::get('/forum/thread/{slug}/feature', 'ForumController@feature')->name('forum.thread.feature');
    Route::get('/forum/thread/{slug}/edit', 'ForumController@edit')->name('forum.edit');
    Route::patch('/forum/thread/{slug}/edit', 'ForumController@update');
    Route::delete('/forum/replies/{slug}', 'ForumController@destroyReply')->name('forum.destroyReply');

    Route::get('/wallet', 'WalletController@index')->name('wallet.index');
    Route::get('/wallet/transactions', 'WalletController@transactions')->name('wallet.transactions');
    Route::get('/wallet/еxchange', 'WalletController@exchange')->name('wallet.exchange');
    Route::post('/wallet/еxchange', 'WalletController@exchangePost');
    Route::get('/wallet/deposit', 'WalletController@deposit')->name('wallet.deposit');
    Route::post('/wallet/deposit', 'WalletController@depositPost');
    Route::get('/wallet/send', 'WalletController@send')->name('wallet.send');
    Route::post('/wallet/send', 'WalletController@sendPost');

    Route::get('/help/support', 'HelpController@support')->name('help.support');
    Route::get('/help/contact', 'HelpController@contact')->name('help.contact');
    Route::get('/help/faq', 'HelpController@faq')->name('help.faq');
    Route::get('/help/ranks', 'HelpController@ranks')->name('help.ranks');
    Route::get('/help/levels', 'HelpController@levels')->name('help.levels');

    Route::get('/experience', 'ExperienceController@index')->name('experience.index');

    Route::get('/armory', 'ArmoryController@index')->name('armory.index');
});

app/Models/Forum/Category.php
<?php

namespace App\Models\Forum;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'forum_categories';
    protected $fillable = ['title', 'full_width', 'minimum_role'];
    protected $with = ['forums', 'redirects'];
    
    public function forums()
    {
        return $this->hasMany(Forum::class);
    }

    public function redirects()
    {
        return $this->hasMany(Redirect::class);
    }
}

/*
background: url(http://i.imgur.com/GM8QjV0.gif);
    color: #e5d1ff;
    font-weight: bold;
    text-shadow: 0 0 0.9em #ffffff;
*/

app/Models/Forum/Forum.php
<?php

namespace App\Models\Forum;

use Illuminate\Database\Eloquent\Model;

class Forum extends Model
{
    protected $table = 'forum_forums';
    protected $fillable = ['category_id', 'title', 'disabled'];
    protected $with = ['threads'];

    public function threads()
    {
        return $this->hasMany(Thread::class)
            ->orderBy('pinned', 'DESC')
            ->orderBy('updated_at', 'DESC');
    }
    
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getThreadCountAttribute()
    {
        return $this->threads->count();
    }
}

app/Models/Forum/Redirect.php
<?php

namespace App\Models\Forum;

use Illuminate\Database\Eloquent\Model;

class Redirect extends Model
{
    protected $table = 'forum_redirects';
    protected $fillable = ['category_id', 'title', 'link'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/Forum/Reply.php
<?php

namespace App\Models\Forum;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    protected $table = 'forum_replies';
    protected $fillable = ['thread_id', 'creator_id', 'content'];
    protected $touches = ['thread'];
    protected $with = ['creator'];
    
    public function thread()
    {
        return $this->belongsTo(Thread::class);
    }

    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Forum/Report.php
<?php

namespace App\Models\Forum;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    protected $fillable = ['user_id', 'reply_id'];
    protected $table = 'forum_reports';

    public function user()
    {
        return $this->hasOne(User::class);
    }

    public function reply()
    {
        return $this->hasOne(Reply::class);
    }
}

app/Models/Forum/Signature.php
<?php

namespace App\Models\Forum;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Signature extends Model
{
    protected $fillable = ['content'];
    protected $table = 'forum_signatures';
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Forum/Thread.php
<?php

namespace App\Models\Forum;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Thread extends Model
{
    use SoftDeletes;

    protected $table = 'forum_threads';
    protected $fillable = ['forum_id', 'creator_id', 'title', 'locked', 'pinned', 'featured', 'views'];
    protected $dates = ['deleted_at'];
    protected $with = ['replies', 'creator'];

    public function forum()
    {
        return $this->belongsTo(Forum::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class)
            ->orderBy('created_at', 'ASC')
            ->orderBy('id', 'ASC');
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function getReplyCountAttribute()
    {
        return $this->replies->count();
    }

    public function getLastReplyPageAttribute()
    {
        $repliesPerPage = 15;
        $pageNumber = (int) ($this->reply_count / $repliesPerPage + 1);
        return $pageNumber;
    }
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use App\Models\Misc\Role;
use App\Models\Forum\Category;
use App\Models\Forum\Forum;
use App\Models\Forum\Reply;
use App\Models\Forum\Thread;
use App\Models\User;
use Illuminate\Http\Request;

class ForumController extends Controller
{
    public function index()
    {
        $userRole = auth()->user()->roles->first()->level;

        $categories = Category::where('minimum_role', '<=', $userRole)->get();

        $topUser = User::leftJoin('forum_replies','users.id','=','forum_replies.creator_id')
            ->selectRaw('users.*, count(forum_replies.creator_id) AS total')
            ->groupBy('users.id')
            ->orderBy('total','DESC')
            ->first();

        return view('forum.index', [
            'categories' => $categories,
            'topUser' => $topUser
        ]);
    }

    public function forum($slug)
    {
        $id = explode('-', $slug)[0];
        $forum = Forum::where('id', $id)->firstOrFail();
        $threads = $forum->threads()
            ->with('replies')
            ->orderBy('pinned', 'DESC')
            ->orderBy('updated_at', 'DESC')
            ->paginate(25);

        $userRole = auth()->user()->roles->first();

        if ($userRole->level >= $forum->minimum_role) {
            return view('forum.forum', [
                'forum' => $forum,
                'threads' => $threads
            ]);
        } else {
            abort(404);
        }
    }

    public function thread($slug)
    {
        $id = explode('-', $slug)[0];
        $thread = Thread::where('id', $id)->with(['replies'])->firstOrFail();
        $thread->increment('views');

        $replies = $thread->replies()
            ->with(['creator'])
            ->orderBy('created_at', 'ASC')
            ->orderBy('id', 'ASC')
            ->paginate(15);

        $userRole = auth()->user()->roles->first();

        if ($userRole->level >= $thread->forum->minimum_role) {
            return view('forum.thread', [
                'thread' => $thread,
                'replies' => $replies
            ]);
        } else {
            abort(404);
        }
    }

    public function new($slug)
    {
        $id = explode('-', $slug)[0];
        $forum = Forum::where('id', $id)->firstOrFail();

        $userRole = auth()->user()->roles->first();

        if ($userRole->level >= $forum->minimum_role) {
            return view('forum.thread-new', [
                'forum' => $forum
            ]);
        } else {
            abort(404);
        }
    }

    public function store(Request $request, $slug)
    {
        $id = explode('-', $slug)[0];
        $forum = Forum::where('id', $id)->firstOrFail();

        $userRole = auth()->user()->roles->first();

        if ($userRole->level >= $forum->minimum_role) {
            $request->merge(['creator_id' => auth()->user()->id]);
            $thread = new Thread($request->all());
            $reply = new Reply($request->all());

            $forum->threads()->save($thread);
            $thread->replies()->save($reply);

            return redirect()->route('forum.thread', $thread->id);
        } else {
            abort(403);
        }
    }

    public function reply(Request $request, $slug)
    {
        $id = explode('-', $slug)[0];
        $thread = Thread::where('id', $id)->firstOrFail();

        $userRole = auth()->user()->roles->first();

        if ($userRole->level >= $thread->forum->minimum_role) {
            $request->merge(['creator_id' => auth()->user()->id]);
            
            $reply = new Reply($request->all());

            $thread->replies()->save($reply);

            return redirect()->route('forum.thread', $thread->id);
        } else {
            abort(403);
        }
    }

    public function destroy(Request $request, $slug)
    {
        $id = explode('-', $slug)[0];
        $junkyard = $this->__settings->forum_junkyard_id;
        $thread = Thread::where('id', $id)->first();

        if ($junkyard != null) {
            $thread->forum_id = $junkyard->value;
            $thread->locked = true;
            $thread->save();

            return redirect()->route('forum.forum', $junkyard->value);
        } else {
            $thread->delete();

            return redirect()->route('forum.forum', $thread->forum->id);
        }
    }

    public function lock($slug)
    {
        $id = explode('-', $slug)[0];
        $thread = Thread::where('id', $id)->first();
        $thread->locked = $thread->locked ? false : true;
        $thread->save();

        return redirect()->route('forum.thread', $id);
    }

    public function pin($slug)
    {
        $id = explode('-', $slug)[0];
        $thread = Thread::where('id', $id)->first();
        $thread->pinned = $thread->pinned ? false : true;
        $thread->save();

        return redirect()->route('forum.thread', $id);
    }

    public function feature($slug)
    {
        $id = explode('-', $slug)[0];
        $thread = Thread::where('id', $id)->first();
        $thread->featured = $thread->featured ? false : true;
        $thread->save();

        return redirect()->route('forum.thread', $id);
    }
}

resources/views/forum/forum.blade.php
@extends('layouts.app')
@section('topbar_active', 'forum')

@section('content')
    <einu-section class="forum">
        <einu-heading class="section-heading">{{ $forum->category->title }} / {{ $forum->title }}</einu-heading>

        <einu-grid>
            <einu-col size="M12 T12 D12" style="padding-top: 0; padding-bottom: 0;">
                {{ $threads->links() }}
                <a style="float: right; background-color: #E69800;" class="button" href="{{ route('forum.new', $forum->id) }}">
                    <einu-icon code="plus"></einu-icon>
                    New thread
                </a>
                <a style="float: right; background-color: #C02C44;" class="button" href="{{ route('forum.new', $forum->id) }}">
                    <einu-icon code="pencil"></einu-icon>
                    Edit forum
                </a>
            </einu-col>

            <einu-col size="M12 T12 D12">
                <einu-block class="section">
                    <einu-heading size="1">{{ $forum->title }}</einu-heading>
                    <einu-table>
                        @foreach ($threads as $thread)
                            <einu-table-row>
                                <einu-table-cell>
                                    <einu-block class="info">
                                        <einu-block class="title">
                                            {!! $thread->locked ? '<span class="thread-status-icon"><einu-icon code="lock"></einu-icon></span>' : '' !!}
                                            {!! $thread->pinned ? '<span class="thread-status-icon"><einu-icon code="thumb-tack"></einu-icon></span>' : '' !!}
                                            {!! $thread->featured ? '<span class="thread-status-icon"><einu-icon code="star"></einu-icon></span>' : '' !!}
                                            <a href="{{ route('forum.thread', $thread->id.'-'.str_slug($thread->title, '-')) }}">{{ $thread->title }}</a>
                                        </einu-block>
                                        <einu-block class="sub-title">
                                            By <a href="{{ route('profile', '@'.$thread->creator->username) }}">{{ $thread->creator->username }}</a>,
                                            {{ \Carbon\Carbon::createFromTimeStamp(strtotime($thread->created_at))->diffForHumans() }}
                                        </einu-block>
                                    </einu-block>
                                </einu-table-cell>
                                <einu-table-cell class="stats_cell">
                                    <einu-block class="stats">
                                        <einu-block>
                                            {{ $thread->reply_count }} {{ $thread->reply_count == 1 ? 'reply' : 'replies' }}
                                        </einu-block>
                                        <einu-block>
                                            {{ $thread->views }} {{ $thread->views == 1 ? 'view' : 'views' }}
                                        </einu-block>
                                    </einu-block>
                                </einu-table-cell>
                                <einu-table-cell class="last_reply_cell">
                                    <einu-block class="last_reply">
                                        <einu-block class="avatar">
                                            <a href="{{ route('profile', '@'.$thread->replies->last()->creator->username) }}">
                                                <img src="{{ asset('storage/avatars/'.$thread->replies->last()->creator->avatar) }}"
                                                    alt="{{ $thread->replies->last()->creator->username }}" />
                                            </a>
                                        </einu-block>
                                        <einu-block class="user">
                                            <einu-block>
                                                <span class="role-{{ strtolower($thread->replies->last()->creator->roles->first()->name) }}">
                                                    <a href="{{ route('profile', '@'.$thread->replies->last()->creator->username) }}">{{ $thread->replies->last()->creator->username }}</a>
                                                </span>
                                            </einu-block>
                                            <einu-block class="date"><a href="{{ route('forum.thread', $thread->id) }}?page={{ $thread->last_reply_page }}#reply-{{ $thread->replies->last()->id }}">{{ \Carbon\Carbon::createFromTimeStamp(strtotime($thread->replies->last()->created_at))->diffForHumans() }}</a></einu-block>
                                        </einu-block>
                                    </einu-block>
                                </einu-table-cell>
                            </einu-table-row>
                        @endforeach
                    </einu-table>
                </einu-block>
            </einu-col>

            <einu-col size="M12 T12 D12" style="padding-top: 0; padding-bottom: 0;">
                {{ $threads->links() }}
                <a style="float: right; background-color: #E69800;" class="button" href="{{ route('forum.new', $forum->id) }}">
                    <einu-icon code="plus"></einu-icon>
                    New thread
                </a>
                <a style="float: right; background-color: #C02C44;" class="button" href="{{ route('forum.new', $forum->id) }}">
                    <einu-icon code="pencil"></einu-icon>
                    Edit forum
                </a>
            </einu-col>
        </einu-grid>
    </einu-section>
@endsection

resources/views/forum/index.blade.php
@extends('layouts.app')
@section('topbar_active', 'forum')

@section('content')
    <einu-section class="forum">
        <einu-heading class="section-heading">Forums</einu-heading>

        <einu-grid>
            @foreach ($categories as $category)
                <einu-col size="M12 {{ $category->full_width ? "T12 D12" : "T12 D12" }}">
                    <einu-block class="section">
                        <einu-heading size="1">{{ $category->title }}</einu-heading>
                        <einu-table>
                            @foreach ($category->redirects as $redirect)
                                <einu-table-row onclick="window.location='{{ $redirect->link }}';">
                                    <einu-table-cell>{{ $redirect->title }}</einu-table-cell>
                                    <einu-table-cell></einu-table-cell>
                                    <einu-table-cell>Something</einu-table-cell>
                                </einu-table-row>
                            @endforeach
                            @foreach ($category->forums as $forum)
                                <einu-table-row>
                                    <einu-table-cell>
                                        <einu-block class="info">
                                            <einu-block class="title">
                                                <a href="{{ route('forum.forum', $forum->id.'-'.str_slug($forum->title, '-')) }}">{{ $forum->title }}</a>
                                            </einu-block>
                                            <einu-block class="sub-title">
                                                {{ $forum->description }}asdasdasd  
                                            </einu-block>
                                        </einu-block>
                                    </einu-table-cell>
                                    <einu-table-cell class="index-post-count">
                                        <einu-block class="count">
                                            <einu-block>{{ $forum->thread_count }}</einu-block>
                                            <einu-block>Posts</einu-block>
                                        </einu-block>
                                    </einu-table-cell>
                                    <einu-table-cell class="last_reply_cell">
                                        @if ($forum->thread_count > 0)
                                            @if ($forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply != null)
                                                <einu-block class="last_reply">
                                                    <einu-block class="avatar">
                                                        <a href="{{ route('profile', '@'.$forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->creator->username) }}">
                                                            <img src="{{ asset('storage/avatars/'.$forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->creator->avatar) }}"
                                                                alt="{{ $forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->creator->name }}" />
                                                        </a>
                                                    </einu-block>
                                                    <einu-block class="user">
                                                        <einu-block>
                                                            <a href="{{ route('forum.thread', $forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->thread->id) }}">
                                                                {{ $forum->threads()->orderBy('updated_at', 'DESC')->first()->title }}
                                                            </a>
                                                        </einu-block>
                                                        <einu-block class="date">
                                                            <a href="{{ route('forum.thread', $forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->thread->id) }}?page={{ $forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->thread->last_reply_page }}#reply-{{ $forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->id }}">
                                                                {{ \Carbon\Carbon::createFromTimeStamp(strtotime($forum->threads()->orderBy('updated_at', 'DESC')->first()->last_reply->created_at))->diffForHumans() }}
                                                            </a>
                                                        </einu-block>
                                                    </einu-block>
                                                </einu-block>
                                            @endif
                                        @endif
                                    </einu-table-cell>
                                </einu-table-row>
                            @endforeach
                        </einu-table>
                    </einu-block>
                </einu-col>
            @endforeach
        </einu-grid>
    </einu-section>
    <einu-section class="forum">
        <einu-heading class="section-heading">Informations</einu-heading>

        <einu-grid>
            <einu-col size="M12 T6 D6">
                <einu-block class="section">
                    <einu-heading size="1">Statistics</einu-heading>
                    <einu-table>
                        <einu-table-row></einu-table-row>
                    </einu-table>
                </einu-block>
            </einu-col>
            <einu-col size="M12 T6 D6">
                <einu-block class="section">
                    <einu-heading size="1">Statistics</einu-heading>
                    <einu-table>
                        <einu-table-row>
                            <einu-table-cell >{{ $topUser->forum_replies()->count() }} posts</einu-table-cell>
                        </einu-table-row>
                    </einu-table>
                </einu-block>
            </einu-col>
        </einu-grid>
    </einu-section>
@endsection

resources/views/forum/thread-new.blade.php
@extends('layouts.app')
@section('topbar_active', 'forum')

@section('content')
    <einu-section class="forum">
        <einu-heading class="section-heading">{{ $forum->category->title }} / {{ $forum->title }}</einu-heading>

        <einu-grid>
            <einu-col size="M12 T12 D12">
                <einu-block class="section">
                    <einu-heading size="1">New thread</einu-heading>
                    <form class="einu-form" method="POST" action="{{ route('forum.new', $forum->id) }}">
                        {{ csrf_field() }}

                        <einu-control-group>
                            <label for="title">Thread title</label>
                            <input type="text" name="title" id="title" />
                        </einu-control-group>

                        <einu-control-group>
                            <label for="content">Thread content</label>
                            <textarea rows="6" name="content" id="content"></textarea>
                        </einu-control-group>

                        @if (auth()->user()->roles->first()->level > 2)
                            <einu-control-group>
                                <einu-block style="padding: 0;">
                                    <input type="checkbox" name="locked" id="locked" value="1" />
                                    <label for="locked">Locked thread</label>
                                </einu-block>
                                <einu-block style="padding: 0;">
                                    <input type="checkbox" name="pinned" id="pinned" value="1" />
                                    <label for="pinned">Pinned thread</label>
                                </einu-block>
                                <einu-block style="padding: 0;">
                                    <input type="checkbox" name="featured" id="featured" value="1" />
                                    <label for="featured">Featured thread</label>
                                </einu-block>
                            </einu-control-group>
                        @endif

                        <einu-control-group>
                            <button class="button" type="submit">Publish</button>
                            <a style="background-color: #C02C44;" class="button" href="{{ route('forum.forum', $forum->id) }}">Back</a>
                        </einu-control-group>
                    </form>
                </einu-block>
            </einu-col>
        </einu-grid>
    </einu-section>
@endsection